name: Hello Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Hello World
        shell: bash
        run: echo "Hello World"

  goodbye:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World
        shell: bash
        run: echo "Goodbye World"

