echo 'name: Hello Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World"
        shell: bash

  goodbye:
    needs: hello  # This ensures goodbye runs after hello
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World"
        shell: bash  

